GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2FyYWgiLCJpYXQiOjE3MTAxOTU2NDksImV4cCI6MTcxMDE5NjI0OX0.8RuKmgk44sQpR3nTS909-GkcBInqT2uSgFZcWU2YaZI
 

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2FyYWgiLCJpYXQiOjE3MTAwMzc0MDN9.oZPKFLmTIrebkQJgFMim1G14nBMTB00COB9KTRVRzYM"

}

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2FyYWgiLCJpYXQiOjE3MTAwMzc0MDN9.oZPKFLmTIrebkQJgFMim1G14nBMTB00COB9KTRVRzYM"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Sarah"
}